name: regression test

on:
  push:
    branches:
      - main

jobs:
    auto-repair:
        runs-on: self-hosted
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: run vulcan action
              uses: Suresoft-GLaDOS/vulcan-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                path: vulcan_target